### ISSUE TITLE
AttributeError when upgrading extension

### ISSUE THREAD

**Issue by Diamondemon** [jupyterlab/extension-template#16]
## Description

When running `python -m jupyterlab.upgrade_extension .`, I get the following error:

```python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/julien/.conda/envs/jupyterlab-ext/lib/python3.11/site-packages/jupyterlab/upgrade_extension.py", line 315, in <module>
    update_extension(args.path, args.vcs_ref, args.no_input is False)
  File "/home/julien/.conda/envs/jupyterlab-ext/lib/python3.11/site-packages/jupyterlab/upgrade_extension.py", line 147, in update_extension
    copier.run_auto(template, output_dir, vcs_ref=vcs_ref, data=extra_context, defaults=True)
    ^^^^^^^^^^^^^^^
AttributeError: module 'copier' has no attribute 'run_auto'
```

## Reproduce

1. Have (or create) a Jupyterlab 3.x.x extension
2. Follow the [migration guide](https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html)

## Expected behavior

Upgrading the extension without an error

## Context

- Operating System and version: Linux EndeavourOS 6.1.32-1-lts
- Browser and version: Firefox 114 
- JupyterLab version: 4.0.1

**Comment by Diamondemon** [comment]
It turns out that it is a version problem with Copier. Following the migration guide leads to installing Copier 8 while the template was made for Copier 7. 

Thus, it is necessary to either fix the Copier version or fix the template and the `jupyterlab.upgrade_extension` code.

**Comment by fcollonval** [comment]
Thanks for reporting @Diamondemon 

JupyterLab 4.0.2 added support for copier v8.
