### ISSUE TITLE
Extension description from user input leads to broken `jlpm build`

### ISSUE THREAD

**Issue by gplasky** [jupyterlab/extension-template#48]
## Description

Following the instructions in the [extension tutorial](https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html), during the `copier copy https://github.com/jupyterlab/extension-template .` step, one is prompted to enter an extension description. If the user enters a single quote anywhere in the description (e.g. as an apostrophe), that will break the extension build when running `pip install -ve .` later in the instructions.
## Reproduce

1. Follow [the extension tutorial](https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html)
2. Run `copier` as instructed.
3. Add an extension description that includes a single quote (`'`) anywhere within.
4. Proceed through the instructions to the build step which has you run `pip install -ve .`
5. Observe the following error during build:

``` 
INFO:hatch_jupyter_builder.utils:> /private/var/folders/yx/49ml7j3s7t31pwd25pyj6rb800n42n/T/pip-build-env-tcyq9c22/overlay/bin/jlpm run install:extension
  src/index.ts(11,59): error TS1005: ',' expected.
```

Inspecting `src/index.ts` at the given line number and character reveals the single quote breaking the `description` k:v pair.

## Expected behavior

Single quotes provided by user in the description (or any user-submitted text) should either be escaped or stripped.

## Context

- Operating System and version: MacOS Ventura
- Browser and version: Chrome 117
- JupyterLab version: 4.0.6
- Extension template version: 4.2.1

**Comment by fcollonval** [comment]
Thanks for reaching out @gplasky 

Would you be willing to open a PR to fix that?

Technically what need to be done is probably to change the code in the following two places:

https://github.com/jupyterlab/extension-template/blob/fcd01842647ba08a29512c940010b4938ba65600/template/package.json.jinja#L4

Should become

```
"description": "{{ project_short_description | replace('"', '\\"') }}"
```

https://github.com/jupyterlab/extension-template/blob/fcd01842647ba08a29512c940010b4938ba65600/template/src/index.ts.jinja#L17


```
 description: '{{ project_short_description | replace("'", "\\'") }}', 
```
