### ISSUE TITLE
CSS nesting rules not working on jupyterlab

### ISSUE THREAD

**Issue by terlan4** [jupyterlab/extension-template#51]
Hi, the problem is modern native CSS supports nesting rules in browsers. but it doesn't work on jupyterlab or jupyter notebooks and I dont know why. Because nested css is included in bundled code, still not working tho. What can be the issue and how can I fix it? (I want to use native CSS rather than SASS, so please do not suggest to use SASS instead. I would rather love to solve the issue)

i've tried nesting rules on jupyterlab local dev, jupyterlab online, jupyter notebook online, jupyterlite online. None worked :((

![image](https://github.com/jupyter/notebook/assets/138553763/0d3a6a4c-9fa3-43c3-ba29-d362b574f3af)
![image](https://github.com/jupyter/notebook/assets/138553763/9ab87efd-e368-445e-805a-e645954664be)

**Comment by krassowski** [comment]
Closing in favour of https://github.com/jupyterlab/jupyterlab/issues/15350. Please do not open the same issue in three different places as instead of answering your question we need to spend time cleaning up.
