### ISSUE TITLE
twine reports "InvalidDistribution: Metadata is missing required fields: Name, Version."

### ISSUE THREAD

**Issue by psychemedia** [jupyterlab/extension-template#68]
Using the template, a build seems to work fine, except for when I try to push to pypi with twine:

```bash
python -m build
twine upload dist/*
```

gives:

```text
ERROR    InvalidDistribution: Metadata is missing required fields: Name, Version.                   
         Make sure the distribution includes the files where those fields are specified, and is     
         using a supported Metadata-Version: 1.0, 1.1, 1.2, 2.0, 2.1, 2.2.    
```

The `package.json` file has `name` and `version` both set.

**Comment by krassowski** [comment]
I do not see this problem. https://github.com/pypi/warehouse/issues/15611 suggests that this may happen when an outdated `pkginfo` is installed. Can you check it you have the latest version of it and twine?

**Comment by psychemedia** [comment]
`pkginfo`, `twine` and `hatchling` were all latest releases. Downgrading to `hatchling==1.21.1` gives a build that `twine` seems to be happy with.

**Comment by psychemedia** [comment]
Ah... seems like `pkginfo` in was outdated in the env twine was calling from...
