### ISSUE TITLE
Update snapshots does not work out of the box

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/extension-template#70]
## Description

The update snapshots job fails in the step using `jupyterlab/maintainer-tools/.github/actions/update-snapshots@v1` action with:

```
Run yarn install
yarn install v1.22.22
// omitted
Run yarn run test:update
yarn run v1.22.22
$ jlpm playwright test --update-snapshots
Internal Error: jupyterlab-my-extension-ui-tests@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
```

Note that `yarn` in the image is now pointing to a very old version of yarn.

Changing `npm_client` to `jlpm` by adding an argument in:

https://github.com/jupyterlab/extension-template/blob/b2e180bf60a786990792401ccc5b0350d140e24f/template/.github/workflows/%7B%25%20if%20test%20%25%7Dupdate-integration-tests.yml%7B%25%20endif%20%25%7D#L45-L50

Fixes the issue for me.

I am not sure if this should be fixed in `maintainer-tools` by ensuring that yarn berry is used, or here by adding `npm_client` argument.

Anyone else seen this?

**Comment by fcollonval** [comment]
I haven't use the template in a while. I would go for your fix setting `npm_client`
