### ISSUE TITLE
Duplicate slashes for URLs generated from the repository URL with a trailing slash

### ISSUE THREAD

**Issue by joaopalmeiro** [jupyterlab/extension-template#74]
Hi! 👋 

## Description

When generating a new extension, if the [`repository` URL](https://github.com/jupyterlab/extension-template/blob/eda2e0db3a8b0630e8802524dd3c95ac7db54526/copier.yml#L67) has a trailing slash (e.g., https://github.com/jupyterlab/extension-template/), the URL in the [`bugs.url` field](https://github.com/jupyterlab/extension-template/blob/eda2e0db3a8b0630e8802524dd3c95ac7db54526/template/package.json.jinja#L12) of the `package.json` file will be generated with two slashes (e.g., https://github.com/jupyterlab/extension-template//issues). Same for the [`repository.url` field](https://github.com/jupyterlab/extension-template/blob/eda2e0db3a8b0630e8802524dd3c95ac7db54526/template/package.json.jinja#L30) (e.g., https://github.com/jupyterlab/extension-template/.git) and the [`Github Actions Status` badge](https://github.com/jupyterlab/extension-template/blob/eda2e0db3a8b0630e8802524dd3c95ac7db54526/template/README.md.jinja#L3) in the `README.md` file (e.g., https://github.com/jupyterlab/extension-template//workflows/Build/badge.svg)

Some kind of normalization (in the [`copier.yml` file](https://github.com/jupyterlab/extension-template/blob/eda2e0db3a8b0630e8802524dd3c95ac7db54526/copier.yml) or in the [`package.json` template file](https://github.com/jupyterlab/extension-template/blob/eda2e0db3a8b0630e8802524dd3c95ac7db54526/template/package.json.jinja)) would be handy from my perspective. Please let me know if I can help in any way.

## Reproduce

1. Generate a new extension (using the `pipx run --pip-args=jinja2-time==0.2.0 copier==9.2.0 copy --trust --vcs-ref v4.3.1 https://github.com/jupyterlab/extension-template demo` command, for example).
2. Fill in the `Git remote repository URL` field with a URL with a trailing slash: `https://github.com/jupyterlab/extension-template/`
3. Check the `bugs.url` and `repository.url` fields of the generated `package.json` file, as well as the `Github Actions Status` badge URL at the top of the `README.md` file.

## Expected behavior

URL repositories without duplicate slashes, whether the repository URL has a trailing slash.

## Context

- Operating System and version: macOS Sonoma 14.2.1
- Browser and version: Chrome 123.0.6312.107
- JupyterLab version: 4.0.9
- Python version: 3.10.13
- Copier version: 9.2.0
- pipx version: 1.5.0

**Comment by krassowski** [comment]
Sounds reasonable, feel welcome to open a PR!
