### ISSUE TITLE
Update `jupyter_server` dependency specifier

### ISSUE THREAD

**Issue by joaopalmeiro** [jupyterlab/extension-template#86]
Hi! 👋 

### Problem

When creating a _server_ extension, `jupyter-server` has the following dependency specifier: `"jupyter_server>=2.0.1,<3"`.
https://github.com/jupyterlab/extension-template/blob/4ddbfc3e7944d48d8f5a1fc058ba5071a4268812/template/pyproject.toml.jinja#L25-L27

However, `jupyterlab` itself defines it a bit more strictly: `"jupyter_server>=2.4.0,<3"` (https://github.com/jupyterlab/jupyterlab/blob/f7ca6ad67e178995a70883ae284ecf5a7efd3d85/pyproject.toml#L45)

### Proposed Solution

Adopt the dependency specifier for `jupyter-server` from the `jupyterlab` package. I haven't faced any issues because of this difference, but I think it would be nice to have "synchronized" dependencies.

Please let me know your opinion and if I can help/open a PR. Thanks!

**Comment by jtpio** [comment]
Thanks @joaopalmeiro for the suggestion :+1: 

Yes, it would be probably not hurt to bump the lower bound for `jupyter_server` to something higher. Please feel free to open a PR, thanks!
